spring.profiles.active: local-h2
spring:
  profiles:
    group:
      "product" : "product,tourapi,tmapapi,real-db"
      "local-h2" : "local-h2,tourapi,tmapapi"
      "local-mysql" : "local-mysql,tourapi,tmapapi"
---

spring:
  config:
    activate.on-profile: local-h2
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
  h2.console.enabled: true
  jpa:
    database-platform: H2
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true
  logging.level.root: trace

---

spring:
  config:
    activate.on-profile: local-mysql
  datasource:
    url: jdbc:mysql://localhost:3306/here_story_test_db[localhost]
    username: root
    password: soo930
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true
  logging.level.root: trace

---
spring:
  config:
    activate.on-profile: product
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true