spring:
  profiles:
    active: local-h2

---

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
  h2.console.enabled: true
  jpa:
    database-platform: H2
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true
  logging.level.root: trace
  profiles: local-h2

spring.profiles.include: tourapi,tmapapi

---

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/here_and_there_testdb
    username: root
    password: soo930
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true
  logging.level.root: trace
  profiles: local-mysql

spring.profiles.include: tourapi,tmapapi

---
spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true
  profiles: product
spring.profiles.include: tourapi,real-db,tmapapi